name: Test CSharp

on:
  push:
    paths:
      - 'CSharp/**'
      - '.github/workflows/CSharp.yml'
  pull_request:
    paths:
      - 'CSharp/**'
      - '.github/workflows/CSharp.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.x

    - name: Set up dependencies
      working-directory: CSharp
      run: dotnet restore

    - name: Build
      working-directory: CSharp
      run: dotnet build --no-restore

    - name: Test
      working-directory: CSharp
      run: dotnet test --no-build --verbosity normal
