name: Test Go

on:
  push:
    paths:
      - 'Go/**'
      - '.github/workflows/Go**'
  pull_request:
    paths:
      - 'Go/**'
      - '.github/workflows/Go**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Test with testify
      working-directory: Go
      run: go test -v
