name: Test JavaScript

on:
  push:
    paths:
      - 'JavaScript/**'
      - '.github/workflows/JavaScript.yml'
  pull_request:
    paths:
      - 'JavaScript/**'
      - '.github/workflows/JavaScript.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Set up dependencies
      working-directory: JavaScript
      run: npm install

    - name: Test
      working-directory: JavaScript
      run: npm test
