name: Test Python

on:
  push:
    paths:
      - 'Python/**'
      - '.github/workflows/Python**'
  pull_request:
    paths:
      - 'Python/**'
      - '.github/workflows/Python**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Test with nose
      working-directory: Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m nose
