name: Test TypeScript

on:
  push:
    paths:
      - 'TypeScript/**'
      - '.github/workflows/TypeScript.yml'
  pull_request:
    paths:
      - 'TypeScript/**'
      - '.github/workflows/TypeScript.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Set up dependencies
      working-directory: TypeScript
      run: npm install

    - name: Test
      working-directory: TypeScript
      run: npm test

    - name: Report using branch name (dynamic, use for a pair on each branch)
      run: |
        export GIT_BRANCH_NAME=$(git symbolic-ref --short HEAD)
        export GIT_BRANCH_NAME=$( echo "$GIT_BRANCH_NAME" | sed 's/ /%20/g' )
        curl -X GET ${{ secrets.PUSH_COUNTER_URL }}/record/$GIT_BRANCH_NAME?build=green
